### ISSUE TITLE
Compiling / Usage on Apple Silicon (M1 / M1 Pro) fails

### ISSUE THREAD

**Issue by fahadysf** [PoloDB/PoloDB#50]
Compiling pypolodb fails on Apple Silicon (M1 Pro tested)
```
python3 setup.py build
running build
running build_ext
building 'polodb' extension
creating build/temp.macosx-12-arm64-3.9
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -Iinclude -I/opt/homebrew/include -I/opt/homebrew/opt/openssl@1.1/include -I/opt/homebrew/opt/sqlite/include -I/Users/fahad/Code/dopetrader-deta/venv/include -I/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c polodb_ext.c -o build/temp.macosx-12-arm64-3.9/polodb_ext.o
creating build/lib.macosx-12-arm64-3.9
clang -bundle -undefined dynamic_lookup -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk build/temp.macosx-12-arm64-3.9/polodb_ext.o /var/folders/0q/jc8d0l0n2jv0fydvx5b_zhzr0000gn/T/polodb_lib/0.10.4/libpolodb_clib.a -L/opt/homebrew/lib -L/opt/homebrew/opt/openssl@1.1/lib -L/opt/homebrew/opt/sqlite/lib -o build/lib.macosx-12-arm64-3.9/polodb.cpython-39-darwin.so
ld: warning: ignoring file /var/folders/0q/jc8d0l0n2jv0fydvx5b_zhzr0000gn/T/polodb_lib/0.10.4/libpolodb_clib.a, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
```

Installing using pip or using the built version gives the same issue:

```
$ python3
Python 3.9.9 (main, Nov 21 2021, 03:16:13)
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import polodb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/fahad/Code/polodbtest/venv/lib/python3.9/site-packages/polodb-0.10.4-py3.9-macosx-12-arm64.egg/polodb.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '_PLDB_arr_get'
>>>
```

**Comment by vincentdchan** [comment]
Which branch are you testing? master?

**Comment by fahadysf** [comment]
Yes I'm using the master branch.

The build and install log is as seen below.

```
❯ python3 setup.py build
running build
running build_ext
❯ python3 setup.py install
running install
/opt/homebrew/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/opt/homebrew/lib/python3.9/site-packages/setuptools/command/easy_install.py:156: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing polodb.egg-info/PKG-INFO
writing dependency_links to polodb.egg-info/dependency_links.txt
writing top-level names to polodb.egg-info/top_level.txt
reading manifest file 'polodb.egg-info/SOURCES.txt'
writing manifest file 'polodb.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-12-arm64/egg
running install_lib
running build_ext
creating build/bdist.macosx-12-arm64/egg
copying build/lib.macosx-12-arm64-3.9/polodb.cpython-39-darwin.so -> build/bdist.macosx-12-arm64/egg
creating stub loader for polodb.cpython-39-darwin.so
byte-compiling build/bdist.macosx-12-arm64/egg/polodb.py to polodb.cpython-39.pyc
installing package data to build/bdist.macosx-12-arm64/egg
running install_data
creating build/bdist.macosx-12-arm64/egg/include
copying include/polodb.h -> build/bdist.macosx-12-arm64/egg/include
creating build/bdist.macosx-12-arm64/egg/EGG-INFO
copying polodb.egg-info/PKG-INFO -> build/bdist.macosx-12-arm64/egg/EGG-INFO
copying polodb.egg-info/SOURCES.txt -> build/bdist.macosx-12-arm64/egg/EGG-INFO
copying polodb.egg-info/dependency_links.txt -> build/bdist.macosx-12-arm64/egg/EGG-INFO
copying polodb.egg-info/top_level.txt -> build/bdist.macosx-12-arm64/egg/EGG-INFO
writing build/bdist.macosx-12-arm64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
__pycache__.polodb.cpython-39: module references __file__
creating 'dist/polodb-0.10.4-py3.9-macosx-12-arm64.egg' and adding 'build/bdist.macosx-12-arm64/egg' to it
removing 'build/bdist.macosx-12-arm64/egg' (and everything under it)
Processing polodb-0.10.4-py3.9-macosx-12-arm64.egg
creating /opt/homebrew/lib/python3.9/site-packages/polodb-0.10.4-py3.9-macosx-12-arm64.egg
Extracting polodb-0.10.4-py3.9-macosx-12-arm64.egg to /opt/homebrew/lib/python3.9/site-packages
Adding polodb 0.10.4 to easy-install.pth file

Installed /opt/homebrew/lib/python3.9/site-packages/polodb-0.10.4-py3.9-macosx-12-arm64.egg
Processing dependencies for polodb==0.10.4
Finished processing dependencies for polodb==0.10.4
 ~/Code/PoloDb/pypolodb > ( master )
 ```
 It seems to not throw any warnings at build time anymore and also installs fine now but trying to use it still throws the symbol not found issue.
 
 ```
 ❯ python3
Python 3.9.9 (main, Nov 21 2021, 03:16:13)
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import polodb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/opt/homebrew/lib/python3.9/site-packages/polodb-0.10.4-py3.9-macosx-12-arm64.egg/polodb.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '_PLDB_arr_get'
>>>
```

**Comment by vincentdchan** [comment]
Since Python support is currently removed. Closed

**Comment by vincentdchan** [comment]
Track this problem in new issue #108
